### ISSUE TITLE
for neo4j integration please also add node labels and relationship-type to graphistry data

### ISSUE THREAD

**Issue by jexp** [graphistry/pygraphistry#101]
currently it only copies id and properties:

```
def bolt_graph_to_edges_dataframe(graph):
    import pandas as pd
    return pd.DataFrame([
        util.merge_two_dicts(
            { key: value for (key, value) in relationship.items() },
            {
                relationship_id_key:    relationship.id,
                start_node_id_key:          relationship.start_node.id,
                end_node_id_key:     relationship.end_node.id
            }
        )
        for relationship in graph.relationships
    ])


def bolt_graph_to_nodes_dataframe(graph):
    import pandas as pd
    return pd.DataFrame([
        util.merge_two_dicts(
            { key: value for (key, value) in node.items() },
            {
                node_id_key: node.id
            }
        )
        for node in graph.nodes
])
```

**Comment by lmeyerov** [comment]
Agreed, both for `pygraphistry` and the direct connector. The type mapping fits naturally, such as with the legend. 

It's a little unclear how we should do labels for the table -- maybe column `label1=True`, and once we support array-types, `label=[label1, ...]`.

**Comment by jexp** [comment]
Sounds good to me

**Comment by jexp** [comment]
Sounds good to me

**Comment by cwharris** [comment]
Deleted a duplicate comment. Didn't realize it would leave a note in it's place, but it makes sense! Backfire! :)

**Comment by lmeyerov** [comment]
![image](https://user-images.githubusercontent.com/4249447/50053153-a5759200-00e4-11e9-8545-2e132b40c782.png)

Looks like the enterprise connector does the right thing out-of-the-box, we just need pygraphistry to do the same. Agreed, let's do it on the arrow branch for jan.

**Comment by lmeyerov** [comment]
Already been in the enterprise studio, and now in notebooks as well with https://github.com/graphistry/pygraphistry/releases/tag/0.9.63 . Win!
