### ISSUE TITLE
Honeypot2 in Python 3

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#130]
Bug in groupby wrangling (referrrer)

**Comment by philipphu** [comment]
if we mean the same thing (second line of code in the first cell of "3. Advanced Bindings") then its fixed by
`attackers_df = df.groupby(['attackerIP']).agg(count = ('count', 'sum')).reset_index()`

**Comment by pradkrish** [comment]
Will you be able to provide more context what needs to be fixed here?

**Comment by lmeyerov** [comment]
Hi @pradkrish  , just ran https://github.com/graphistry/pygraphistry/blob/master/demos/demos_by_use_case/logs/Tutorial%20Part%202%20(Apache%20Logs).ipynb , and saw:

- [ ] stale register instructions:
```python
#graphistry.register(key='<go to www.graphistry.com/api-request to get one api key>', server='labs.graphistry.com')
```
Should point users to `...(api=3, username=...`, similar to other demos

- [ ] exn on `referer = grouped_logs['referer'].agg(mostFrequent)` breaks following cells

In general, the pandas code there is a little clumsy relative to modern pandas, so can use some code golfing :)

**Comment by pradkrish** [comment]
Thanks, I am able to reproduce it. I will look into it.

**Comment by pradkrish** [comment]
@lmeyerov  Try replacing 

`referer = grouped_logs['referer'].agg(mostFrequent)` with

`referer = grouped_logs['referer'].agg(pandas.Series.mode).to_frame('referer')`

and check if you are satisfied with the output you see. If you are, I can send a PR.
