### ISSUE TITLE
Support for visualizing hypergraphs?

### ISSUE THREAD

**Issue by epideveloper** [graphistry/pygraphistry#139]
Does PyGraphistry support the creation of hypergraph visualizations?

**Comment by lmeyerov** [comment]
Hi @epideveloper  , yes , see the examples of `graphistry.hyphergraph(...)` on the mainpage, and run `help(graphistry.hypergraph)` for its docs. Note the two modes, `direct=True`, and the default of `direct=False`, and the ability to control which properties to link and how.
