### ISSUE TITLE
[FEA] StreamLit support

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#159]
V1: 
-- Likely just via `st.markdown(iframe_html_str, unsafe_allow_html=True)`
-- Primarily as docs  demos:
  * Minimal
  * Interactive dashboard
  * Self-contained docker project
  * As a Graphistry sibling service (jwt auth, ...)

V2: 
-- When `st` client API gets released, see if we can combine either via dynamic filters (client) or dynamic dataframes (server)

Cross-link: https://github.com/streamlit/streamlit/issues/1418#issuecomment-652266644

**Comment by lmeyerov** [comment]
WIP:

![streamlit_graphistry](https://user-images.githubusercontent.com/4249447/87355073-918a5000-c514-11ea-9ac8-5a4ae7696bf1.png)

**Comment by jonherke** [comment]
THIS is ACTUALLY AWESOME!

**Comment by lmeyerov** [comment]
Prove out continuing in https://github.com/graphistry/graph-app-kit . 

Still unclear what actual pygraphistry component support should be based on usage patterns:

-- graphistry self-hosted: reuse of auth etc
-- component: make `graphistry.plot()` work as a `st.write` or component
-- caching support: maybe do a multi-stage version, where plot (upload) creates a cachable rep

**Comment by lmeyerov** [comment]
Closing in favor of https://github.com/graphistry/graph-app-kit . Once the dynamic graph api comes out, we should revisit for dynamic filters + dynamic data!
