### ISSUE TITLE
Support for undirected graphs?

### ISSUE THREAD

**Issue by jiagengliu** [graphistry/pygraphistry#163]
If I understand correctly, the plotter only supports directed graphs. I wonder if there's a plan for undirected graphs, or if there's a workaround. Thanks!

https://github.com/graphistry/pygraphistry/blob/master/graphistry/plotter.py#L543

**Comment by lmeyerov** [comment]
@jiagengliu  Missed this ---

You can use existing controls for handling undirected behavior:

* The layout algorithm is undirected
* For rendering to hide use of directed-ness, you can
- hide arrows
- set curvature to 0

There is (currently) no way to do both undirected & directed settings at the same time, however

Does that help / anything additional? I'll close for now and happy to re-open
