### ISSUE TITLE
No module named 'Graphistry'

### ISSUE THREAD

**Issue by akash-kaul** [graphistry/pygraphistry#166]
When trying to import graphistry in Google Colab, I get the error that the module graphistry is not found. I've done `!pip install graphistry -q` and the package downloads properly, but when trying to import the package it errors out. I know graphistry has support for Google Colab, so I'm wondering if a new update has interfered with the Colab capabilities. Any ideas would be greatly appreciated.

![Screen Shot 2020-08-13 at 12 27 09 PM](https://user-images.githubusercontent.com/46678528/90166817-663b9080-dd60-11ea-8e8b-583354796699.png)

**Comment by LucasAlegre** [comment]
What was the solution?

**Comment by lmeyerov** [comment]
Hi @LucasAlegre , Jupyter & Colab generally require you to restart the runtime after installing a package for it to be visible:

![image](https://user-images.githubusercontent.com/4249447/126802338-d35b4c62-27b9-45cc-b79f-6909884e2a80.png)

If that doesn't work, happy to reopen and investigate with you!
