### ISSUE TITLE
Using an old API key?

### ISSUE THREAD

**Issue by NetwarSystem** [graphistry/pygraphistry#173]
I have an API key I was given but it's from eighteen months ago, and I was busy with an Elasticsearch implementation at the time. That is now fairly mature, I'm working with ArangoDB, and am curious to see how I can bring content from there into a graph I can embed. I just tried the key, but code has changed a bit, I'm not sure if it still works. Is there a specific place for developers to apply?

**Comment by lmeyerov** [comment]
Check out Graphistry Hub for that -- https://www.graphistry.com/get-started:

-- Use a email form (vs. social login) so you can get a username/password, vs one of the self-expiring tokens (1hr)

-- Upon logging into a new account, it'll show a sample of using the `.register(api=3, username=.., password=...)` combo

Also note that, as part of the migration to `api=3` (under-the-hood: Apache Arrow + Nvidia RAPIDS), it is more strict about  homogeneous data columns, so if there are errors, you should check that columns aren't mixing types
