### ISSUE TITLE
Error while building the documentation

### ISSUE THREAD

**Issue by khmariem** [graphistry/pygraphistry#181]
I have tried building the documentation in a virtual environment using python3.8, I get however complaints about the annotations in the code. I made sure that in the venv I am running pyhon3 but it's not working.
I get the following message after running `./build.sh` :
```
SKIPPING  ../setup.py ../graphistry/util.py
File source/versioneer.rst already exists, skipping.
File source/graphistry.rst already exists, skipping.
File source/modules.rst already exists, skipping.
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.3.6

Configuration error:
There is a syntax error in your configuration file: invalid syntax (pygraphistry.py, line 156)
Makefile:55: recipe for target 'html' failed
make: *** [html] Error 1
./build.sh: 9: [: Linux: unexpected operator

```

How can I locally test and build the documentation? Thank you!

**Comment by lmeyerov** [comment]
@khmariem Thanks for noticing, see new helper `docker.sh` in https://github.com/graphistry/pygraphistry/pull/183

**Comment by lmeyerov** [comment]
(And, let me know if there is a related project we should be taking to support that triggered this!)
