### ISSUE TITLE
How does one set the point color?

### ISSUE THREAD

**Issue by richardehughes** [graphistry/pygraphistry#189]
I have tried a number of things and I can't get the point color to work.   I tried using the marvel example and that does not color the nodes properly either - the graphic after:
g3.plot(unique_coappearences,  nodes_colored)
yields a graph in which all of the nodes are black.

I also tried:
g = g.encode_point_color('pcolor', palette=['#000', '#00F', '#0F0', '#0FF', '#FFF'], as_categorical=True)
g.plot(links_df,nodes_df)

and then I tried remapping the column 'pcolor' so that it held the colors directory and did:
g = g.bind(point_color='pcolor')
g.plot(links_df,nodes_df)

Nothing worked.   Is there a simple example that shows how to color the nodes?

I am using python 3.6.8

**Comment by lmeyerov** [comment]
@richardehughes Thanks for pointing out the tutorials here needed a refresh for the latest features -- as a start, I added a set on a simplified example here: https://github.com/graphistry/pygraphistry/blob/master/demos/more_examples/graphistry_features/encodings-colors.ipynb 

I'm going to close this immediate issue, but if more questions, happy to help. Also, for this type of question, Slack may be a good choice for faster responses!
