### ISSUE TITLE
print out current set of bindings

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#20]
Now that the bindings are not explictly set at each call, it'd help to be able to printf the set of bindings active at a particular point. 

Proposal 1:

`graphistry.bind(...)` :  setter that returns `graphistry` with updated bindings
`graphistry.bind()` : getter that returns `{<k> : <v>}`

Proposal 2:
A top-level field `bindings` that is the dictionary of current bindings. 

`graphistry.bindings` : returns `{<k>: <v>}`

I'm leaning towards Proposal 2.

**Comment by thibaudh** [comment]
I think the pretty printing code for the plotter is enough
