### ISSUE TITLE
Document minimum python version 

### ISSUE THREAD

**Issue by jberryman** [graphistry/pygraphistry#203]
It looks like 3.6+ since I'm getting an error from some string interpolation, but I don't have deep python experience.

**Comment by lmeyerov** [comment]
@jberryman  Thank you for noting this was a challenge!

Currently, the Python 3.6+ requirement is listed at:
*Beginning of the github landing page / readme.md
* The setup.py classifiers
* PyPI repo docs

Where were you looking / where might have helped?

**Comment by jberryman** [comment]
Here would probably have been useful: https://github.com/graphistry/pygraphistry#install

It's not in the readme (unless I'm blind)

Thanks!

**Comment by lmeyerov** [comment]
Thanks! It's reasonable to have something there as a point-in-time thing. 

For future reference in this and other projects, a quick convention here seems to be via the badge status project summary on the ~first line:

![image](https://user-images.githubusercontent.com/4249447/107253977-b633a100-69eb-11eb-938e-30866bfb2366.png)

**Comment by lmeyerov** [comment]
Just added spot:

![image](https://user-images.githubusercontent.com/4249447/107256102-eb40f300-69ed-11eb-8abb-792836e5cd99.png)


I'm thinking maybe an explicit hw/sw requirements docs would be helpful, similar to the server's (https://github.com/graphistry/graphistry-cli/blob/master/hardware-software.md) . Created https://github.com/graphistry/pygraphistry/issues/210 for that.

I think that's it for now, unless you have further spots etc that may help, so will close. Either way, thank you for sharing your experience!
