### ISSUE TITLE
parameter graph is confusing

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#21]
`graphistry.plot(graph=..., nodes=...)` confuses me.

A bit of bike shedding, but, to me, 

`G = (V, E)`

So, I expect parameters nodes/vertices to be V, edges to be E, and if there's a G, to be combined (V, E).  For example, maybe igraph/networkx objects are a G.

**Comment by lmeyerov** [comment]
@thibaudh can we close? i think `graph` now feeds both `nodes` and `edges`, while `nodes`/`edges` are explicitly about just nodes/edges.

**Comment by thibaudh** [comment]
Sure It makes sense to reverse the edges/nodes parameters: (E, V) instead of the commonly used (V, E) because nodes are optional but edges are not.
