### ISSUE TITLE
SSL proxy for prod

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#23]
( + @thibaudh  )

Matt, we need to get the https proxy up as part of the API 1.0 release. This will, in turn, trigger so code changes. Can you let me know when that happens?

(HTTPS proxy should be up for both prod & staging. They currently use diff code paths, and I'd like to unify.)

**Comment by lmeyerov** [comment]
@int3h where are we on this?

**Comment by thibaudh** [comment]
Moving issue to deploy.
