### ISSUE TITLE
[BUG] Node/edge colors not running

### ISSUE THREAD

**Issue by Cedricyf** [graphistry/pygraphistry#241]
**Describe the bug**
When setting the node or edge color, the figure only show the black color (using the exact code for the honeydot example)
**To Reproduce**

**Browser environment (please complete the following information):**
 - OS: mac
 - Browser chrome

**PyGraphistry environment**
 - Version 0.19.0
 - Python Version 3.8
 - Where run  jupyter
![Screen Shot 2021-07-09 at 12 10 37 PM](https://user-images.githubusercontent.com/37076023/125113949-ed979e00-e0ae-11eb-88e8-9445eda39933.png)

**Comment by lmeyerov** [comment]
Thank @Cedricyf  !

We have a regression on the free Graphistry Hub relating to a bunch of library upgrades yesterday -- are you on Hub or a private server?

**Comment by lmeyerov** [comment]
@Cedricyf 

I took a look -- can you try setting `graphistry.register(api=3, username='...', password='...')` at the top and rerun? This may be an issue around using `api=1`, which we can help with

Later today, will be releasing a new version of this notebook that is in a more modern style, including explicitly using `api=3` features

**Comment by Cedricyf** [comment]
Hi @lmeyerov,
What I have used is api=3 with my username and password. I just tried the new version, the color is still black/white and I used numeric value for the point_color parameter.
Thank you!

**Comment by lmeyerov** [comment]
I opened https://github.com/graphistry/pygraphistry/issues/243 to help here and will mark this as closed

If can help further, or this isn't what's going on, would be happy to help!
