### ISSUE TITLE
[BUG] name 'Edge' is not defined

### ISSUE THREAD

**Issue by UrYuWang** [graphistry/pygraphistry#253]
import graphistry
    
graphistry.register(api=3, protocol="https", server="hub.graphistry.com", username="xxx", password="xxx")

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-5-c77d15e69502> in <module>
----> 1 import graphistry
      2 
      3 graphistry.register(api=3, protocol="https", server="hub.graphistry.com", username="***", password="***")

/opt/anaconda3/lib/python3.8/site-packages/graphistry/__init__.py in <module>
----> 1 from graphistry.pygraphistry import (  # noqa: E402, F401
      2     client_protocol_hostname, protocol, server,
      3     register, login, refresh, api_token, verify_token,
      4     store_token_creds_in_memory,
      5     name, description,

/opt/anaconda3/lib/python3.8/site-packages/graphistry/pygraphistry.py in <module>
     13 from . import util
     14 from . import bolt_util
---> 15 from .plotter import Plotter
     16 
     17 import logging

/opt/anaconda3/lib/python3.8/site-packages/graphistry/plotter.py in <module>
      1 from .PlotterBase import PlotterBase
      2 from .compute import ComputeMixin
----> 3 from .gremlin import GremlinMixin, CosmosMixin, NeptuneMixin
      4 from .layouts import LayoutsMixin
      5 

/opt/anaconda3/lib/python3.8/site-packages/graphistry/gremlin.py in <module>
    193 #https://github.com/apache/tinkerpop/blob/master/gremlin-python/src/main/python/gremlin_python/structure/graph.py
    194 def flatten_edge_structure(
--> 195     edge: Edge,
    196     src_col: str = 'src', dst_col: str = 'dst',
    197     label_col: str = 'label', id_col: str = 'id'

NameError: name 'Edge' is not defined

**Comment by lmeyerov** [comment]
@UrYuWang  Thanks for catching this -- we were likely testing with Gremlin installed, which we've been adding more support for, but that's an optional dependency

For interim fixes, you can either:

- install gremlinpython (`pip install --user gremlinpython`)
- go back a few versions, likely `pip install --user graphistry==0.18.2`

**Comment by UrYuWang** [comment]
gremlinpython should not be optional.

**Comment by lmeyerov** [comment]
Yeah I think the fixes are:

- docs: for gremlin users, recommend `graphistry[gremlin]` if they do not have gremlinpython already
- core: make gremlin plugin optional, probably initially by some type hackery, and as plugins keep clearing up, into separate modules
- infra: more careful core vs plugin testing - https://github.com/graphistry/pygraphistry/issues/254

same issue w/ neo4j plugin

**Comment by lmeyerov** [comment]
Hi @UrYuWang , this is fixed in 0.19.4 (https://github.com/graphistry/pygraphistry/pull/255), so should Just Work next time you are installing from a clean system. Let me know if the problem reappears!
