### ISSUE TITLE
[BUG] In line 1275 of PlotterBase.py, there is a "." instead of a ","

### ISSUE THREAD

**Issue by LucasAlegre** [graphistry/pygraphistry#257]
**Describe the bug**
In line 1275 of PlotterBase.py, there is a "." instead of a ",":

                return g._make_dataset(e, n, name, description, mode, metadata. memoize)

**To Reproduce**

Run any code that plot an igraph.Graph.
'''
graphistry.bind(source='src', destination='dst').plot(g)
'''

**Actual behavior**

AttributeError                            Traceback (most recent call last)
<ipython-input-36-d6708a0e1eeb> in <module>()
----> 1 graphistry.bind(source='src', destination='dst').plot(g)

1 frames
/root/.local/lib/python3.7/site-packages/graphistry/PlotterBase.py in _plot_dispatch(self, graph, nodes, name, description, mode, metadata, memoize)
   1273             if isinstance(graph, igraph.Graph):
   1274                 (e, n) = g.igraph2pandas(graph)
-> 1275                 return g._make_dataset(e, n, name, description, mode, metadata. memoize)
   1276         except ImportError:
   1277             pass

AttributeError: 'NoneType' object has no attribute 'memoize'

**Browser environment (please complete the following information):**
 - OS: Ubuntu
 - Browser: Any
 - Version: Last version

**Graphistry GPU server environment**
 - Google Colab

**Comment by lmeyerov** [comment]
Hi @LucasAlegre  thanks for reporting -- now fixed in  https://github.com/graphistry/pygraphistry/pull/258 and released as part of 0.19.5!
