### ISSUE TITLE
[BUG] igraph community generate black nodes

### ISSUE THREAD

**Issue by LucasAlegre** [graphistry/pygraphistry#259]
**Describe the bug**
igraph community generate black nodes

**To Reproduce**
The example on README
```python
ig = graphistry.pandas2igraph(links)
ig.vs['pagerank'] = ig.pagerank()
ig.vs['community'] = ig.community_infomap().membership
Bind node data to visual node attributes
We can then bind the node community and pagerank columns to visualization attributes:
g.bind(point_color='community', point_size='pagerank').plot(ig)
```

**Expected behavior**
Each node should have a different color depending on the community

**Actual behavior**
Every node is black

**Browser environment (please complete the following information):**
 - OS: Ubuntu
 - Browser chrome
 - Version Last Version

**Graphistry GPU server environment**
 - Googe colab

**Comment by lmeyerov** [comment]
@LucasAlegre  I don't have this in front of me, but can you check:

is `g._nodes.info()` showing `community` as `int32` or `int64` ? Built-in palettes are `int32`, and rgb hex are `int64` (`0xFF00FF00` == `rgb(255,0,255)`)

If `int64`, you can try:

```python
g = g.nodes(g._nodes.assign(community=g._nodes['community'].astype('int32')))
g.plot()
```

**Comment by LucasAlegre** [comment]
@lmeyerov I can't do this, as I'm passing an igraph.Graph to "plot" method. So I don't have access to g._nodes before calling "plot(ig)".

**Comment by lmeyerov** [comment]
Gotcha -- we have helpers for that kind of thing, and indeed looks like the 64bit hex -> 32bit palette remapping:

```python
ig = ...
g_empty = graphistry.bind(source='src', destination='dst', node='__nodeid__')
(e_df, n_df) =  g_empty.igraph2pandas(ig)
g = g_empty.nodes(n_df).edges(e_df)
```

And to transform a `g`'s nodes/edges dataframes:

```python
g = g.nodes(lambda g: g._nodes.assign(community=g._nodes['community'].astype('int32')))
g.plot()
```
