### ISSUE TITLE
[BUG] Notebooks use api=1 auth

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#265]
**Describe the bug**
Some demos use api=1/2 instead of api=3

**To Reproduce**
See main analyst notebook

**Expected behavior**
Should instead have something like:

```python
# To specify Graphistry account & server, use:
# graphistry.register(api=3, username='...', password='...', protocol='https', server='hub.graphistry.com')
# For more options, see https://github.com/graphistry/pygraphistry#configure

**Comment by pradkrish** [comment]
is it about changing it in all the examples in the `demos/` folder ?

**Comment by lmeyerov** [comment]
Yep -- anywhere that advocates using `register(key=...` or `register(api=1` or `register(api=2` s deprecated in favor of  `api=3` (Apache Arrow + JWT)!

**Comment by pradkrish** [comment]
Okay, you can assign it to me, I am working on it.

**Comment by pradkrish** [comment]
By the way, if it's not too much of a bother, will you be able to give me some background on why this api value means why it has changed? Thanks.

**Comment by lmeyerov** [comment]
Awesome!

Yes -- the newer versions of Graphistry use:

* Apache Arrow for significantly faster & safer uploads. `api=1` was `json` (slow + untyped), `api=2` was protobufs (janky, hard optimize, & few data types), and `api=3` supports Arrow (but also supports different format JSON via new URLs)

* JWT tokens, which we've been introducing for deeper & more standard authentication + authorization. `api=3` is the only one that supports it

So `api=1` / `api=2` are deprecated, and we'll be making `api=3` default (breaking change) + fully removing old versions sometime 2022.

**Comment by lmeyerov** [comment]
Solved with https://github.com/graphistry/pygraphistry/pull/280, thank you! 🎊
