### ISSUE TITLE
[BUG] Error for pandas memoization is confusion

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#267]
**Describe the bug**

A user asked questions about the following error:

```
Failed memoization speedup attempt due to Pandas internal hash function failing. Continuing without memoization speedups
```

We can give a more constructive response like `... This is fine, but for speedups around skipping re-uploads of previously seen tables, try identifying which columns have types that Pandas cannot hash, and convert them to hashable types like strings.`

**Comment by Mohitkumar6122** [comment]
@lmeyerov, Could you tell me more about this issue, I'd love to contribute to your project!
