### ISSUE TITLE
Extend color palette so that cluster > 12 are not all black

### ISSUE THREAD

**Issue by thibaudh** [graphistry/pygraphistry#27]

**Comment by lmeyerov** [comment]
Done! (+ @thibaudh @padentomasello )

See https://github.com/graphistry/graphistry.com/commit/b7ad1efbeb0ca124cad7f1fca3859d2b820b0bc3 and https://github.com/graphistry/graph-viz/commit/40330007abab3aa0d3d415e21caec0c7f2ae7f93 

Starts @ 265000 . Repeats the 12-color palette (offset 0) 10,000 times. Slight tweak to the doc generator to not actually repeat doc palette 10,000 times.

**Comment by LucasAlegre** [comment]
Hi,

This is happening again in the current version.

Any thoughts?

**Comment by lmeyerov** [comment]
You can see the `int32` values @ https://hub.graphistry.com/docs/api/api-color-palettes/  . Note that it's still sparse, e.g., 12-999 are black 

Typically, and what the in-tool UI color pickers do, palettes would be something like:

```python
palette_base =96000
palette_len = 7 
g = (
  g.nodes(g._nodes.assign(c=(g._nodes['community'] % palette_len) + palette_base).astype('int32'))
  .bind(point_color='c'))
g.plot()
```

Or use a custom continuous/categorical mapping, or your own rgb column: https://github.com/graphistry/pygraphistry/blob/master/demos/more_examples/graphistry_features/encodings-colors.ipynb
