### ISSUE TITLE
how to unbind an attribute?

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#28]
(+ @thibaudh @padentomasello )

I bound `point_size` for one graph, and wanted to unbind for another, and couldn't: setting `g.bind(point_size=None)` is ignored. I don't think this is the expected behavior..

**Comment by thibaudh** [comment]
So far I have never needed to unbind an attribute. What is the usecase for this?

**Comment by lmeyerov** [comment]
Don't recall, but it happened to me maybe once, twice. It's easy to work around, but "surprising". Quick googling didn't show this is detectable tho.

**Comment by briantrice** [comment]
Resetting a binding makes total sense from my perspective. "going back to equal sizing so that visually some other dimension pops out [like color]".

Python can tell the difference between an omitted parameter and one set to None, too.

**Comment by quinnhj** [comment]
I agree -- rebinding/unbinding is something that I'd expect as well.

**Comment by briantrice** [comment]
This code pattern won't allow it, so that's what to address. Could use a special "Unbound" object:
        res._point_size = point_size or self._point_size

**Comment by lmeyerov** [comment]
@briantrice:
 
> Python can tell the difference between an omitted parameter and one set to None, too.

This seems most intuitive. I had tried googling for this, any pointers?

**Comment by briantrice** [comment]
It works if you use splat args, **kwargs, then you can say "key not in kwargs:". Our current call structure doesn't admit this, and I'm inclined to recommend Unbound so that calls can be partial specifications.

**Comment by lmeyerov** [comment]
@padentomasello can you assign a priority to this? i personally haven't encountered since then

**Comment by lmeyerov** [comment]
Unbinding is doable via `g._point_color = None`, etc.
