### ISSUE TITLE
document url_params and height settings

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#29]

**Comment by lmeyerov** [comment]
+ @briantrice @thibaudh @quinnhj @trxcllnt @padentomasello 

Are we dropping the URL parameters entrypoint to customization? I believe Brian is against URL parameters.

**Comment by briantrice** [comment]
I'm in favor of everything but HTML/JS injection. :)

**Comment by quinnhj** [comment]
+1 for everything but html/js injection

**Comment by lmeyerov** [comment]
I think new JS API work will supersede this. I presume URL params will be part of that, including documentation.
