### ISSUE TITLE
highlights within notebooks often swallowed

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#32]
Hard to reproduce (more common on @padentomasello )

Likelihood: JS-level, not CSS, as label hovers work.

Guess of fix: set z-index of pygraphistry's generated iframe.

**Comment by lmeyerov** [comment]
@thibaudh Are you still getting this? Seems to be fine for me now..

**Comment by thibaudh** [comment]
Not sure, will keep an eye on it.

**Comment by lmeyerov** [comment]
Closing, happy to reopen if still an issue.
