### ISSUE TITLE
install  pygraphistry togoogle colab

### ISSUE THREAD

**Issue by SalvatoreRa** [graphistry/pygraphistry#321]
Hi,

I have used succesfully on my personal laptop, but I need to use in Colab. How I can use pygraphistry in Colab?

I have try to install in Google Colab with
`!pip install  graphistry`
`!apt install  graphistry`0

Every time it print that it successfully installed but then when running:

`import graphistry`

I receive error:

> ModuleNotFoundError: No module named 'graphistry'

thanks for the help

**Comment by lmeyerov** [comment]
Hi @SalvatoreRa -- Colab often requires restarting the runtime before new imports become accessible

**Comment by SalvatoreRa** [comment]
actually a few tentative and it worked, the only problem is that it gets stuck in loading the graph, it blocks in loading at 30%. the graph is around 2000 nodes and 4000 edges (the cora dataset that I am using for a test)

**Comment by lmeyerov** [comment]
Hm strange -- we try to catch validation errors ahead of time, do you have something we can reproduce, ideally ipynb + data + stuck url? If in pandas: `pd.to_csv(..)` or better, `pd.to_parquet(..)`

**Comment by SalvatoreRa** [comment]
weirdly enough I tried to reload the same script and it worked perfectly (loaded fast and smoothly)

**Comment by lmeyerov** [comment]
Great! Will close for now, can always reopen
