### ISSUE TITLE
Reading graph

### ISSUE THREAD

**Issue by GSunilc** [graphistry/pygraphistry#328]
I want to read a graph such that i will give x co-ordinate and in output it should print y co-ordinate where the x and the line meets .is it possible plz help.

**Comment by lmeyerov** [comment]
I'm not sure what that means, can you provide psuedocode? This sounds more like a scientific calculator than graph analytics..

**Comment by GSunilc** [comment]
I want to read this graph by giving x co-ordinate and line.in output it
should give y co-ordinate.is it possible.

**Comment by lmeyerov** [comment]
I don't understand, but the underlying `g._nodes` and `g._edges` tables are exposed

**Comment by GSunilc** [comment]
Simple bro i just want to import that graph and give
 input :x co-ordinate, a specific line
 Output : y coordinate
Is it possible or converting that graph in to excel sheet and there by
interpolation is easy.

**Comment by lmeyerov** [comment]
Ah I see

```python

g = graphistry.read_csv('edges.csv', 's', 'd')
g2 = g.tree_layout()  # some layout
lines = g2._edges[ g2._edges['id'] == some_line ]
attributed_lines = (
  lines.merge(
    g2._nodes.rename(columns={'x': 'sx', 'y': 'sy', g2._node: 's'}),
    on='s',
    how='left')
.merge(
    g2._nodes.rename(columns={'x': 'dx', 'y': 'dy', g2._node: 'd'}),
    on='d',
    how='left')
)
```

1. from there you have a line and can interpolate

2. if doing server layouts, more work to get the serverside layout (vs notebook-side tree_layout() ), but doable

But I'd still use a python scientific calculator, this seems rather indirect...

**Comment by GSunilc** [comment]
Thanks bro,i well try it.

**Comment by GSunilc** [comment]
Bro ,i have a python code for vehicles detection using opencv.but i am
unable to Classify vehicles based on their size.plz help me bro ......
It's important for me bro , plz help me in classification..


import cv2

import numpy as np


min_contour_width=40  #40

min_contour_height=40  #40

offset=10       #10

line_height=550 #550

matches =[]

vehicles=0

def get_centroid(x, y, w, h):

    x1 = int(w / 2)

    y1 = int(h / 2)


    cx = x + x1

    cy = y + y1

    return cx,cy

    #return (cx, cy)



#cap = cv2.VideoCapture(0)

cap = cv2.VideoCapture('video.mp4')

#cap = cv2.VideoCapture('Relaxing highway traffic.mp4')




cap.set(3,1920)

cap.set(4,1080)


if cap.isOpened():

    ret,frame1 = cap.read()

else:

    ret = False

ret,frame1 = cap.read()

ret,frame2 = cap.read()



while ret:

    d = cv2.absdiff(frame1,frame2)

    grey = cv2.cvtColor(d,cv2.COLOR_BGR2GRAY)

    #blur = cv2.GaussianBlur(grey,(5,5),0)

    blur = cv2.GaussianBlur(grey,(5,5),0)

    #ret , th = cv2.threshold(blur,20,255,cv2.THRESH_BINARY)

    ret , th = cv2.threshold(blur,20,255,cv2.THRESH_BINARY)

    dilated = cv2.dilate(th,np.ones((3,3)))

    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (2, 2))


        # Fill any small holes

    closing = cv2.morphologyEx(dilated, cv2.MORPH_CLOSE, kernel)

    contours,h =
cv2.findContours(closing,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

    for(i,c) in enumerate(contours):

        (x,y,w,h) = cv2.boundingRect(c)

        contour_valid = (w >= min_contour_width) and (

            h >= min_contour_height)


        if not contour_valid:

            continue

        cv2.rectangle(frame1,(x-10,y-10),(x+w+10,y+h+10),(255,0,0),2)



        cv2.line(frame1, (0, line_height), (1200, line_height), (0,255,0),
2)

        centroid = get_centroid(x, y, w, h)

        matches.append(centroid)

        cv2.circle(frame1,centroid, 5, (0,255,0), -1)

        cx,cy= get_centroid(x, y, w, h)

        for (x,y) in matches:

            if y<(line_height+offset) and y>(line_height-offset):

                vehicles=vehicles+1

                matches.remove((x,y))

                print(vehicles)



    cv2.putText(frame1, "Total vehicles Detected: " + str(vehicles), (10,
90), cv2.FONT_HERSHEY_SIMPLEX, 1,

                    (0, 170, 0), 2)








    #cv2.drawContours(frame1,contours,-1,(0,0,255),2)



    cv2.imshow("Original" , frame1)

    #cv2.imshow("Difference" , th)

    if cv2.waitKey(1) == 27:

        break

    frame1 = frame2

    ret , frame2 = cap.read()

#print(matches)

cv2.destroyAllWindows()

cap.release()

**Comment by lmeyerov** [comment]
this sounds like a cv2 q, recommend you look there

Potentially related, we are working with some orgs on graph neural networks, and that can make sense in some routing scenarios, but that's more of an R&D customer thing unfortunately given the complexity

**Comment by GSunilc** [comment]
Hoo ,i try a lot but no one is responding so that I thought you would help.
Thanks for the reply bro.

**Comment by GSunilc** [comment]
Bro if you don't mind ,Can you suggest any one you know it's some what
important and urgent too..
Plz help me if you can

**Comment by GSunilc** [comment]
Bro if you don't mind ,Can you suggest any one you know it's some what
important and urgent too..
Plz help me if you can

**Comment by lmeyerov** [comment]
upwork.com is pretty fast for this stuff ! we have a services division, but guessing not as appropriate here

**Comment by GSunilc** [comment]
Cool, thanks bro !
