### ISSUE TITLE
Warning when uploading large graphs

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#33]
+ @thibaudh @briantrice 

We have two interesting inflection points for graph size:

~1MM nodes + edges: client quality degrades
~8MM nodes or ~8MM edges: client hit testing becomes undefined

I'm wondering when IPython should warn vs. error . The second is definitely an error for now -- should the first also be?

**Comment by briantrice** [comment]
Ref. https://github.com/graphistry/graph-viz/issues/69 for followon work.
