### ISSUE TITLE
Make the default plotted graph exportable by default

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#34]
- @thibaudh @briantrice @padentomasello @int3h 

When plotting, we should make the default 'more friendly' for exporting as HTML. For example, imagine laying out for a few seconds & auto-saving, and the next time the same URL is loaded, start "offline" from that point. Likewise, an in-visualization save (new camera angle, added filters, ...) would update that visualization. The result is that, when I'm "done" with a notebook, I can just hit "export as html" without having to do anything special and it'll "just work".

Does this seem feasible, ideas on ~workarounds, ...? We may need StreamGL to cooperate a bit and be a bit smarter, but similar to the auto-splashscreen & play, seems doable.

**Comment by briantrice** [comment]
Just to clarify on scope, this sounds like an auto-save feature tied to the URL (+parameters and some subset of client authentication). It could target S3 or the server/cluster filesystem.

It's possible that my work to bundle a workbook would provide a sufficient key for auto-save. I'll make a ticket for that, since the groundwork is only laid now, and filter work will proceed ahead of it.

**Comment by lmeyerov** [comment]
PyGraphistry has an API key, and when we call etl from the python notebook, we get a key. However, we don't get the static path key..

I think the additional weirdness here is that etl should return a ~static url, yet:

-- use the time trick similar to the splash screen to not actually be static the first time around
-- that first time around, auto-save after a bit
-- make sure that subsequent saves (autosaves?) reuse the static path

**Comment by briantrice** [comment]
That sounds like we need to talk through this flow together to understand the scope. It's achievable, but needs a coherent scheme of operation.

**Comment by lmeyerov** [comment]
Yes. And, asking for a pony, exports may merit switching to a PNG preview for the splash screen.

**Comment by lmeyerov** [comment]
This looks like it'll be part of the gov work via named & saveable workbooks.
