### ISSUE TITLE
Expose external hook for embedders

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#35]
- @thibaudh @briantrice 

I'm trying to externally control a generated graphistry iframe, and so it'd be really dandy to work with it. A few options:

-- allow specifying HTML attributes (id, name, class); I think we only expose `style` and `url_params`
-- provide default class and gensym id
-- wrap into whatever widget system IPython and others are using and match that interface

**Comment by briantrice** [comment]
I think a simple scheme of postMessage and addEventListener would be sufficient unless you need to thread control-flow back and forth. In which case a promise-chain arrangement with an API wrapper class is a good idea. Is that what you're aiming for?

**Comment by lmeyerov** [comment]
That's good for after the element is created. This is more about how to give a handle for the embedder to refer to it. Today, we return the string `<iframe src=...{?custom_user_param=custom_user_val...}`, but may want to also do say `<iframe id={custom_user_id_or_a_default} attr=...`...

**Comment by briantrice** [comment]
Okay, so this is about the iframe element itself. Specifying the id and class of the iframe element itself is perfectly fine (with gensym defaults). We could encapsulate that with a lightweight JS type (single file, few hundred LOC, to manage the iframe in a less fiddly way).

**Comment by thibaudh** [comment]
We don’t even return <iframe src=… because our endpoints are a mess. Tthey change depending on the protocol chosen (http or https). As a temporary kludge, we emit and iframe without the src attribute and a little <script> that will set the src attribute depending on how the main page is opened.

Before anything, I think we need to fix this mess.

**Comment by lmeyerov** [comment]
This seems to be less of an issue now due to graphistryjs. May reopen later for integrating w/ notebook frameworks like bokeh.
