### ISSUE TITLE
Hint to set notebook to Trusted

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#36]
( @thibaudh : can you take, or should I?)

When opening a third-party notebook, our viz won't be shown because our JS won't run by default.

I propose either:

A) Print out warning/hint HTML to do `File -> Trusted Notebook` and then have JS delete that warning

B) Load an iframe URL and then have our existing iframe js logic overwrite it.

Leaning towards A due to embedding issues motivating the JS logic.

**Comment by thibaudh** [comment]
Since HTTP/HTTPS endpoints have been merged, the iframe can be loaded without javascript, thus notebooks no longer need to be trusted. Closing.
