### ISSUE TITLE
[FEA] org_name support for File POSTs

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#362]
dataset uploads pass org_name but afaict file uploads do not

----

Good: Dataset path:
https://github.com/graphistry/pygraphistry/blob/bb8dd2483d01f2f9dc7b9e1a640cc803ac569ec2/graphistry/arrow_uploader.py#L247

```python
graphistry.register(..., org_name=x)
graphistry.nodes(df, 'n').edges(df2, 's', 'd').plot()
```

---

Missing: When files are made as individual `File` objects:

```python
graphistry.register(..., org_name=x)
graphistry.nodes(df, 'n').edges(df2, 's', 'd').plot(as_files=True)
```

https://github.com/graphistry/pygraphistry/blob/bb8dd2483d01f2f9dc7b9e1a640cc803ac569ec2/graphistry/ArrowFileUploader.py#L72

**Comment by lmeyerov** [comment]
@vaimdev  just checking in here -- didn't see a commit on this?

**Comment by vaimdev** [comment]
Update: it is already in org_sso_login
