### ISSUE TITLE
Python keywords cannot be used as fields of edges. 

### ISSUE THREAD

**Issue by padentomasello** [graphistry/pygraphistry#37]
When I try to create a graph of the following single row dataframe (converted to dictionary):

`{'count(1)': {19834: 2},
 'destinationAddress': {19834: u'63.240.185.216'},
 'destinationUserName': {19834: u'constructor'},
 'min(startTime)': {19834: u'19 Oct 2015 23:37:32 EDT'},
 'name': {19834: u'An account failed to log on.'},
 'sourceAddress': {19834: None},
 'timeUniform': {19834: 19686.0}}`

I receive the following error: 

ValueError                                Traceback (most recent call last)
<ipython-input-148-fd62c907503b> in <module>()
      1 plotter = graphistry.bind(source='destinationUserName', destination='destinationAddress')
----> 2 plotter.plot(hsldf[19834:19835])

/home/DCSAC/g.paden/.local/lib/python2.7/site-packages/graphistry/plotter.pyc in plot(self, graph, nodes)
    303 
    304         PyG = pygraphistry.PyGraphistry
--> 305         dataset = PyG._etl(dataset)
    306         viz_url = PyG._viz_url(dataset['name'], dataset['viztoken'], self._url_params)
    307 

/home/DCSAC/g.paden/.local/lib/python2.7/site-packages/graphistry/pygraphistry.pyc in _etl(dataset)
    160         jres = response.json()
    161         if jres['success'] is not True:
--> 162             raise ValueError('Server reported error:', jres['msg'])
    163         else:
    164             return {'name': jres['dataset'], 'viztoken': jres['viztoken']}

ValueError: ('Server reported error:', u'Illegal value for Message.Field .VectorGraph.edges: .VectorGraph.Edge (Error: Illegal value for Message.Field .VectorGraph.Edge.src of type uint32: function (not an integer))') 

I believe it's because the destinationUserName is 'constructor' which I think is interpreted as a function and not a string. The binding are created using 

'plotter = graphistry.bind(source='destinationUserName', destination='destinationAddress')'

**Comment by padentomasello** [comment]
Thibaud, I'm unfamiliar with the ETL code so I assigned this to you. I'm happy to take this and start learning if you'd like however.

**Comment by thibaudh** [comment]
That bug is actually in ETL worker. Will fix there.
