### ISSUE TITLE
[BUG] g.register(org_name) not functional in some  cases

### ISSUE THREAD

**Issue by webcoderz** [graphistry/pygraphistry#373]
**Describe the bug**
g.register() for various configurations are not working as expected.

**To Reproduce**
Code, including data, than can be run without editing:

```
pip install git+https://github.com/graphistry/pygraphistry@org_sso_login --user
graphistry.__version__ #check to make sure branch version
graphistry.register(api=3, protocol="https", server="", username="", password=""), #works
graphistry.register(api=3, protocol="https", server="", username="", password="", token="")  #works
graphistry.register(api=3, protocol="https", server="",username="", password="",idp_name="", token="") #works
graphistry.register(api=3, protocol="https", server="", username="", password="",idp_name="")    #works

#the next g.register()'s do not work
graphistry.register(api=3, protocol="https", server="", token="") #doesnt work
graphistry.register(api=3, protocol="https", server="",username="", password="",org_name="", token="")#doesnt work
graphistry.register(api=3, protocol="https", server="", username="", password="",org_name="")  #doesnt work

```

**Expected behavior**
What should have happened

g.register() shouldve registered in all cases

**Actual behavior**

What did happen
it didnt work in some cases

**Screenshots**
If applicable, any screenshots to help explain the issue
![image](https://user-images.githubusercontent.com/19884161/179298592-46384f43-903b-40a2-917c-79dde61682df.png)
![image](https://user-images.githubusercontent.com/19884161/179298606-81a88759-30a0-444c-868f-f96c8d637816.png)
![image](https://user-images.githubusercontent.com/19884161/179298641-792c4783-8e46-4024-ba75-08343efa059f.png)
![image](https://user-images.githubusercontent.com/19884161/179298656-62d7c29c-6f69-4869-9776-4196d54f2bce.png)
![image](https://user-images.githubusercontent.com/19884161/179298673-1f920402-dfa1-46ad-97d1-20ba7985e844.png)

**Browser environment (please complete the following information):**
 - Browser [e.g. chrome, safari] chrome latest

**Graphistry GPU server environment**
 - Where run [e.g., Hub, AWS, on-prem] aws eks [demo notebook](https://eks-dev2.grph.xyz/notebook/lab/tree/demos/for_analysis.ipynb)
 - If self-hosting, Graphistry Version [e.g. 0.14.0, see bottom of a viz or login dashboard]
- If self-hosting, any OS/GPU/driver versions

**PyGraphistry API client environment**
 - Where run [e.g., Graphistry 2.35.9 Jupyter]  graphistry juypter
 - Version [e.g. 0.14.0, print via `graphistry.__version__`]
'0.26.1+39.gec009c7'

 - Python Version [e.g. Python 3.7.7] 
 - python3.8

**Additional context**

**Comment by lmeyerov** [comment]
Looks like for bugs:

- [ ] standalone token
- [ ] org_name

**Comment by lmeyerov** [comment]
(in testing)

**Comment by lmeyerov** [comment]
org uploads work, i think the issue is sso, so moving projects
