### ISSUE TITLE
[BUG] g.name not naming or organizing visuals by user/ org name properly

### ISSUE THREAD

**Issue by webcoderz** [graphistry/pygraphistry#374]
**Describe the bug**
1-3 sentences is fine 💪
g.name not naming or organizing visuals by user/ org name properly

**To Reproduce**
Code, including data, than can be run without editing:
pip install git+https://github.com/graphistry/pygraphistry@org_sso_login --user
import graphistry
graphistry.register(api=3, protocol="https", server="", username="", password="",idp_name="")

```python
import pandas as pd
import graphistry
#graphistry.register(api=3, username='...', password='...')
#load data 
idp_name = "Site_wide_SSO_Provider"
g.name(f'plot with {idp_name}')
g.plot()

graphistry.edges(pd.from_csv('https://data.csv'), 's', 'd')).plot()
```

**Expected behavior**
What should have happened
shouldve named the plot "plot with {idp_name}"

**Actual behavior**
What did happen
did not name plot "plot with {idp_name}"

**Screenshots**
If applicable, any screenshots to help explain the issue
![image](https://user-images.githubusercontent.com/19884161/179299410-1469a9fd-5951-403b-b4f8-0cac521c6a72.png)
![image](https://user-images.githubusercontent.com/19884161/179299434-330165d0-ffe8-4079-bb5c-adca26b26aa6.png)

**Browser environment (please complete the following information):**

chrome latest

**Graphistry GPU server environment**
 - Where run [e.g., Hub, AWS, on-prem] AWS EKS
 - If self-hosting, Graphistry Version [e.g. 0.14.0, see bottom of a viz or login dashboard]
- If self-hosting, any OS/GPU/driver versions

**PyGraphistry API client environment**
 - Where run [e.g., Graphistry 2.35.9 Jupyter] graphistry juypter
 - Version [e.g. 0.14.0, print via `graphistry.__version__`] 
 - '0.26.1+39.gec009c7'
 - Python Version [e.g. Python 3.7.7] 
 - python3.8

**Additional context**

see [demo notebook](https://eks-dev2.grph.xyz/notebook/lab/tree/demos/for_analysis.ipynb)

**Comment by lmeyerov** [comment]
Working as expected -- functional updates, so should be

```python
g1 = g.name('zzz')
g1.plot()
```

or `g.name('zzz').plot()`

but not

```python
g1 = g.name('zzz')
g.plot()
```
