### ISSUE TITLE
ERROR. standard_library.install_aliases()

### ISSUE THREAD

**Issue by zihaolucky** [graphistry/pygraphistry#39]
Hi, I got an error when import graphistry

```
import graphistry
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-ace3a50e6850> in <module>()
----> 1 import graphistry

build/bdist.linux-x86_64/egg/graphistry/__init__.py in <module>()

build/bdist.linux-x86_64/egg/graphistry/pygraphistry.py in <module>()

AttributeError: 'module' object has no attribute 'install_aliases'
```

How can I fix this?

**Comment by thibaudh** [comment]
Hi,

Very strange… Which version of pip and python are you using?

Thibaud

**Comment by lmeyerov** [comment]
Also, happy to invite to our slack #channel to help figure it out!

**Comment by zihaolucky** [comment]
Thanks for your generous help :)

```
$ pip --version
pip 7.1.2 from /home/zihao.zzh/packages/anaconda2/lib/python2.7/site-packages (python 2.7)
$ python --version
Python 2.7.10 :: Anaconda 2.4.0 (64-bit)
```

**Comment by thibaudh** [comment]
Happy to help! Hum, those version numbers are fine.

`install_aliases` is provided by the `future` package. It could be that your local version of the package it too old. Could you try upgrading the future package to the latest version (0.15.x)? `pip install --upgrade future` should work.

**Comment by zihaolucky** [comment]
```
sudo pip install --upgrade future
```
and get:
```
Requirement already up-to-date: future in /home/zihao.zzh/packages/anaconda2/lib/python2.7/site-packages/future-0.9.0-py2.7.egg
```

**Comment by thibaudh** [comment]
The latest version of future is 0.15.2 (http://python-future.org/index.html <http://python-future.org/index.html>) Maybe your anaconda distribution needs to be updated. You could try:

 pip install --upgrade pip
 pip install --upgrade graphistry

The latest version of PyGraphistry requires future >= 0.15

**Comment by lmeyerov** [comment]
Yep, Anaconda should have 0.15.2: http://docs.continuum.io/anaconda/pkg-docs .

**Comment by zihaolucky** [comment]
Aha, thank you~ I would try it later.
