### ISSUE TITLE
[FEA] Is there an convenient way to plot an series Node which contains different Attributes

### ISSUE THREAD

**Issue by Tender2233** [graphistry/pygraphistry#418]
On the demo page.I find the `g = g.bind(node='nodeId').nodes(nodes)` way to provides node in the edges. The nodes is an dataframe which forms as cols and rows.
But I have some data in hand which have many attributes and some attributes in some nodes is not apprear in the other node, if I use the dataframe to describe these data,most of the cel will be None.Also, I will meet the problem: data type in one column may be different.
Is there any api could help me?

**Comment by lmeyerov** [comment]
Right now they'll need to be together --

* I can imagine namespacing the columns names with a prefix/suffix to solve the type issue

* We are examining adding support for the ability to pick which fields appear based on entity type, and more control on showing nulls/nans, but no ETA
