### ISSUE TITLE
[BUG] Got 400 or page load error when plot data

### ISSUE THREAD

**Issue by Tender2233** [graphistry/pygraphistry#419]
**Describe the bug**
Sometimes request meets 400 but reply:
```
 {"data":{"args":{"compression":null,"dataset_id":"cf0fd6c9aea24e4c97d5bf4c19115199"},"error_message":"CUDA error encountered at: /workspace/.conda-bld/work/cpp/src/interop/from_arrow.cu:138: 700 cudaErrorIllegalAddress an illegal memory access was encountered"},"error_code":400,"message":"Failed to parse","success":false}
```
The problem above is out my control.
Sometimes in page: Error loading dataset: Contact staff to check error logs for problematic columns or rows (60%)

**To Reproduce**
Related to issue https://github.com/graphistry/pygraphistry/issues/418 .
Meet this problem when column it reach 64,and row is 7,and most of the cel is Nan.
Most of the cel contains value is string or number,only one suspicious is an empty list( [] )

**Additional context**

**Comment by lmeyerov** [comment]
Thanks @Tender2233 , interim you can work around via `df[col] = df[col].astype(str)`, and we'll try to reproduce our side

We recently added categorical dtype support, and this may be nearby.
