### ISSUE TITLE
Visualizing DNA variation graphs

### ISSUE THREAD

**Issue by ekg** [graphistry/pygraphistry#42]
@lmeyerov

[vg](https://github.com/ekg/vg) is a system for working with sequence graphs that represent populations of genomes. There is wide support for this idea in genomics, and it is on the cusp of use in production contexts that are not well served by exisiting approaches based around a single reference genome sequence (such as the human MHC or in species with high diversity, like mosquitoes).

I have developed [techniques to visualize variation graphs](https://github.com/ekg/vg/wiki/visualization) but these rely on graph sunsetting operations to visualize larger graphs and eventually meaningful examination if an entire graph breaks down. I'd be interested in seeing what graphistry is doing to handle this kind of use!

**Comment by lmeyerov** [comment]
Hi @ekg this sounds great! I've met with UCSF and ISB folks before, but never saw this idea. Will send an API key, would love to make this happen :)
