### ISSUE TITLE
413 client error

### ISSUE THREAD

**Issue by epelofske-student** [graphistry/pygraphistry#423]
**Describe the bug**
Large graphs throw a `requests.exceptions.HTTPError: 413 Client Error` when attempting to graph the data. 

**To Reproduce**
I do not have self contained code to reproduce this because the graphs are from a private database

**Expected behavior**
No error

**Actual behavior**
Error

**Browser environment (please complete the following information):**
 - OS: macOS
 - Browser N/A
 - Version 0.28.5

**PyGraphistry API client environment**
 - Where run 0.28.5 python3 script
 - Version 0.28.5
 - Python Version 3.9.12

**Comment by lmeyerov** [comment]
Yes, that is likely hitting the size limit in MB
