### ISSUE TITLE
include cuCat in ai deps

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#444]

**Comment by dcolinmorgan** [comment]
confused how to test the cuCat opt-in install under ai deps if i need to install from cuCat branch ... guess I should branch from graph-ai not master?

**Comment by lmeyerov** [comment]
I think branching from master is ok, not sure why not?

This ticket is about `pip install graphistry[ai]` including cuCat, which in turn (pre-pypi support) should be a github tag target

**Comment by dcolinmorgan** [comment]
ok i think i have the right form [here](https://github.com/graphistry/pygraphistry/blob/cuCat/setup.py#L43)

i was trying to check using `pip install git+https://github.com/graphistry/pygraphistry/@cuCat` but then i think it misses the [ai] part

**Comment by silkspace** [comment]
Was this resolved?

**Comment by lmeyerov** [comment]
Looks like this is / may be getting finished with the current work

**Comment by dcolinmorgan** [comment]
yes, I merged this from an early branch into [tanmoys #486  already](https://github.com/graphistry/pygraphistry/blob/feat/gpu-featurization/setup.py#L47) at setup.py#L47
