### ISSUE TITLE
[BUG] layout nav links to compute package

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#458]
**Describe the bug**

The compute mixn shows up in the nav... but under the link layout some reason. The nav link should say `compute.ComputeMixin`

![Screenshot from 2023-04-03 15-26-15](https://user-images.githubusercontent.com/4249447/229640724-2e8d13d1-4f31-46db-8b95-0bc9b53fb2c4.png)

**Comment by 7h3-3mp7y-m4n** [comment]
is the issue still on ? if yes then can I work on it ?
