### ISSUE TITLE
Keep column names instead of renaming to Source and Destination. 

### ISSUE THREAD

**Issue by padentomasello** [graphistry/pygraphistry#47]
While doing bipartite graphs of IP address -> Alert name for example, it'd be nice to keep the column names so you can refer to them in histograms and filters. (I found myself confused for a few seconds when I didn't see alert names in the histograms). 

Food for thought: this will get more complicated as we move past bipartite. I imagine wanting to have a histogram for each type of node. For bipartite graphs, we have this functionality because we have the concept of source and destination. 

@thibaudh: I'm assigning myself, since I thought this might be a nice project to start with this code base. Maybe we can chat to see if this is appropriate (and something we even want to do) and what the right way to do this is.

**Comment by briantrice** [comment]
Yes, this would be excellent. Source+Destination form the data into a graph, so are like an encoding.

**Comment by lmeyerov** [comment]
+ @quinnhj 

Ooof, Paden is right: we thought about k-partite for filters, but I at least forgot about histograms. On that note, wonder if how we should represent in the data inspector.

**Comment by lmeyerov** [comment]
Moving to new Arrow representation.
