### ISSUE TITLE
[BUG]  cybersecurity-slim triggering umap and other bugs

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#472]
Tried running cybersecurity-slim.ipynb on the merge branch as part of umap + gnn testing:

* UMAP not memoizing ( cc @silkspace  )
* Complaining that `G = g4.DGL_graph` is `None`

**Comment by lmeyerov** [comment]
Happening on latest branch too

**Comment by tanmoyio** [comment]
DGL_graph has been changed into _dgl_graph

**Comment by lmeyerov** [comment]
tx, can you fix?

also, take a look at why memoizing isn't triggering anymore?

**Comment by lmeyerov** [comment]
works now, tx!
