### ISSUE TITLE
[BUG] chavisimo demo doesn't download data

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#474]
Cell with call `download_chavismo_data()` does not populate an existing `data/`

**Comment by silkspace** [comment]
There is a flag:

`df = download_chavismo_data(get_fresh=False)  # set to True to get latest data
`

I wonder why that is not on your end?

**Comment by lmeyerov** [comment]
it's set to `False` so we should default it to `True`, right?

also, then after I flipped it to true, looks like newer pandas / xls reader need new params, now I get with base 2.40.7:

```
File /opt/conda/envs/rapids/lib/python3.8/site-packages/pandas/io/excel/_base.py:1656, in ExcelFile.__init__(self, path_or_buffer, engine, storage_options)
   1652     ext = inspect_excel_format(
   1653         content_or_path=path_or_buffer, storage_options=storage_options
   1654     )
   1655     if ext is None:
-> 1656         raise ValueError(
   1657             "Excel file format cannot be determined, you must specify "
   1658             "an engine manually."
   1659         )
   1661 engine = config.get_option(f"io.excel.{ext}.reader", silent=True)
   1662 if engine == "auto":

ValueError: Excel file format cannot be determined, you must specify an engine manually.
```


trying `engine='xlrd'` and `engine='openpyxl'` did not work

not a blocker for release, but means this demo is broken

**Comment by lmeyerov** [comment]
I had to manually convert to csv but after that worked
