### ISSUE TITLE
[BUG] cuml umap OOM issue

### ISSUE THREAD

**Issue by tanmoyio** [graphistry/pygraphistry#480]

**Comment by lmeyerov** [comment]
maybe cucat , umap, & embed in gpu mode can do a basic OOM precheck , like a default-on exn/warning if expected to fail based on df byte size / number rows & edges vs nv stats?

**Comment by lmeyerov** [comment]
after this release, our distro should start experimenting with the bigger-than-memory rmm modes (autospilling, autopaging, ...) but too early here

**Comment by tanmoyio** [comment]
https://github.com/graphistry/pygraphistry/pull/482
