### ISSUE TITLE
Get graph result

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#485]
Currently, getting a table result is doable

* We should support getting paired node & edge dataframes back, ideally as graph objects:

```python
import graphistry

def query_graph(query: str, named_params: json) -> graphistry.Plottable:

   edges_df, src_col, dst_col = ...
   nodes_df, node_col = ...

   return (graphistry
      .edges(edges_df, src_col, dst_col)
      .nodes(nodes_df, node_col))
```

* If only nodes or only edges are available, it's ok to specify only one of `nodes()` or `edges()`

* If a  type/label is known, it should be given column name 'type'

* If a value type like float vs datetime is known, it should be matched to the corresponding pandas/arrow types

* A few sample queries should be provided

**Comment by tanmoyio** [comment]
exact query or fuzzy ? @lmeyerov

**Comment by lmeyerov** [comment]
This is in the context of Neptune cypher queries , so exact
