### ISSUE TITLE
Graphs with spaces in names won't render

### ISSUE THREAD

**Issue by DavidJBianco** [graphistry/pygraphistry#49]
Given a call to plot() like the following:

>graph.plot(edges, nodes, name="somename")

The above code works and renders a graph in Jupyter Notebook.  However, the following does not:

>graph.plot(edges, nodes, name="some name")

It just hangs at "Herding stray GPUs" forever.  The only difference is the space in the graph name.

**Comment by lmeyerov** [comment]
Thanks for catching -- need to take care of end-to-end encoding here.

Can @briantrice @thibaudh coordinate for S3? (And heads up to @quinnhj , @int3h for other file systems)

**Comment by lmeyerov** [comment]
Also: if the full fix will be significant, can we start with either throwing an error or string mangling?

**Comment by briantrice** [comment]
I don't think this bug belongs to PyGraphistry. I think it's a graph-viz bug. [another reason against multiple repos and filing bugs at the entry point]

**Comment by briantrice** [comment]
graph-viz, on load, decodes the dataset URL parameter but then re-encodes it because it supports both names and URLs. I'll try to disentangle that, which should fix this.

**Comment by briantrice** [comment]
Fix: https://github.com/graphistry/graph-viz/commit/bc525e2e786f68fe9e2f978678872d7e9e17d55a

**Comment by briantrice** [comment]
This should work on staging now.
