### ISSUE TITLE
Set API key based on local user profile, if available

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#51]
IPython already has a notion of user built in, so rather than each user baking in their API key (and the setting getting confused when notebooks get shared), dynamically lookup the API key based on who is logged into IPython. 

This has been becoming a bit of an issue in practice in team settings. 

( + @thibaudh @padentomasello @briantrice )

**Comment by lmeyerov** [comment]
( + @quinnhj  )

Another option is finally add in a login system.

**Comment by thibaudh** [comment]
Are you sure IPython is user-aware? JupyterHub certainly is, but we cannot assume Hub.

I have been wanting to store API keys in a database for a while. With all the time we have been spending manually creating keys and maintaining our spreadsheet, it would have been already been implemented :)

**Comment by thibaudh** [comment]
Closing since we now have a workaround via environment variables thanks to @briantrice
