### ISSUE TITLE
Fix Color specification from the notebook environment

### ISSUE THREAD

**Issue by briantrice** [graphistry/pygraphistry#52]
Let's deprecate the server-side enforcement of an arbitrary color space (https://graphistry.com/palette.html) and just give Python users tools to specify better colors so that the server doesn't have to double-encode and double-decode a color space no one else uses.

ColorLover exists for Python and does what we need:
http://moderndata.plot.ly/color-scales-in-ipython-notebook/

https://github.com/jackparmer/colorlover

**Comment by lmeyerov** [comment]
<3

Do ETL1 and ETL2 support RGB / RGBA somehow now? I'm happy to whip up examples if so.

**Comment by briantrice** [comment]
No, they force all color through the translation process to my great chagrin.

**Comment by lmeyerov** [comment]
I think we should have a discussion on getting ETL2 in as it unlocks a lot of this stuff pretty easily AFAICT and we can deprecate all of ETL1.

**Comment by thibaudh** [comment]
Agreed about deprecating ETL1 and fixing this for ETL2. Colorlover looks great. Lets make ETL2 block on this.

**Comment by lmeyerov** [comment]
(Happy to do documentation stuff when we have have it working again)

**Comment by lmeyerov** [comment]
@briantrice can we close?

**Comment by lmeyerov** [comment]
`api=3` supports rgba ints, so user-level palettes are now doable
