### ISSUE TITLE
More graceful iframe loading failure handling

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#53]
( + @thibaudh @padentomasello @briantrice )

If the iframe fails to load, such as due to mixed protocol, we need a more helpful user experience. 

Proposals:
1. A FAQ (on pygraphistry?), which includes common reasons for this case
2. A heartbeat / timeout as part of the JS API, and have the iframe loader give the hints in case of failure.

To support offline mode of `pygraphistry`, parts of the answer need to be self-contained.

Ideas?

**Comment by lmeyerov** [comment]
(This might also be more application wide: maybe there are some common errors we should propagate in a more structured manner across the various APIs)

**Comment by thibaudh** [comment]
The solution would be to use the same protocol as the outer frame. I will do that as soon as we roll out the merged HTTPS HTTP endpoints.

**Comment by lmeyerov** [comment]
cc @trxcllnt , you may notice some of this while doing js api work

**Comment by thibaudh** [comment]
Our endpoints now support both HTTP and HTTPS. I have also just added a `certificate_validation` to bypass certificate validation when the certs are self-signed.

We should have iframe loading failure anymore (at least not due to mixed content). Closing

**Comment by lmeyerov** [comment]
This issue is more about graceful handling of errors, e.g., user reporting & guidance, than mitigating any particular ones.

**Comment by thibaudh** [comment]
We have solved all the specific issues prompted the creation of this ticket. When another issue comes up, let's open a ticket specifically for it. I find vague/catch all/wishful thinking tickets useless.

**Comment by thibaudh** [comment]
To clarify my thinking: you cannot really have a generic handler in the outer-frame, because any JS code placed in output cells only run if the notebook is truster.

**Comment by lmeyerov** [comment]
A few examples that may involve pygraphistry, not just core:

* Notebook was not marked as trusted; default HTML could suggest what to do here (and be replaced on JS execution)
* Viz uses a server that the user does not have access to; JS timesout and replaces non-loading iframe with a timeout message
* Weird enterprise firewalls breaking connectivity before enough of app initialized

**Comment by briantrice** [comment]
I am kind of with @thibaudh on the policy of not shoving design discussions into the forum threads of a single bug. And this does keep happening. I know an error-handling policy is usually too low-level for product design but there are a multitude of issues to balance.

**Comment by lmeyerov** [comment]
Our new loader + graphistryjs iframe API solve this.
