### ISSUE TITLE
ModuleNotFoundError: No module named 'graphistry.utils' [BUG] 

### ISSUE THREAD

**Issue by ad1arsh** [graphistry/pygraphistry#535]
**Describe the bug**
Upon downloading the latest version (0.32.0) and importing graphistry, there is a no module found error for `graphistry.utils`. Specifically under `graphistry/compute/ASTSerializable.py`, the line `from graphistry.utils.json import JSONVal, serialize_to_json_val` now fails as there is no graphistry.utils file anymore. 

**To Reproduce**
Code, including data, than can be run without editing:

```python
import graphistry
```

**Expected behavior**
Import should happen without issues

**Actual behavior**
There is a no module found error for `graphistry.utils`. Specifically under `graphistry/compute/ASTSerializable.py`, the line `from graphistry.utils.json import JSONVal, serialize_to_json_val` now fails as there is no graphistry.utils file anymore. 

**Screenshots**
![image](https://github.com/graphistry/pygraphistry/assets/45038622/1e1f620f-f5cb-4cb0-9afd-d746ccfb801a)

**Graphistry GPU server environment**
 - Where run [AWS]

**PyGraphistry API client environment**
 - Where run [Graphistry 0.32.0 Jupyter]
 - Version [0.32.0]
 - Python Version [Python 3.10]

**Comment by ad1arsh** [comment]
Downgrading to graphistry 0.31.1 works

**Comment by lmeyerov** [comment]
Thanks, already fixed in https://github.com/graphistry/pygraphistry/pull/532

**Comment by lmeyerov** [comment]
I just merged the PR and published 0.33.0 should be good to go (and now with more GPU acceleration)

Thanks for the heads up!

![Screenshot from 2023-12-27 00-13-20](https://github.com/graphistry/pygraphistry/assets/4249447/15b2b233-1225-4784-b820-0c92acc203e9)
