### ISSUE TITLE
Make sure that column names are valid identifiers

### ISSUE THREAD

**Issue by thibaudh** [graphistry/pygraphistry#55]

**Comment by lmeyerov** [comment]
+ @briantrice @quinnhj 

What is meant here? Brian added support for identifiers via some escaping via `[`,`]`, `[edge:my name with spaces]`.

**Comment by briantrice** [comment]
I don't think we need to validate any user input : just treat it as its own namespace so it cannot collide with Graphistry-system identifiers. e.g. if the user says "type", it should not confuse our notion of "type".

**Comment by briantrice** [comment]
There's also the notion of saving for the user what column an attribute designates in a source system so queries can be generated against it vs what display name a user would like to work with it in (arbitrary string) and finally a description that makes a good tooltip/explanation for non-system-architects.

**Comment by thibaudh** [comment]
Yes, column names live in their own independent namespace. I thought we might still want to normalize column names a little bit to make them compatible with a future formula language. Should we really let users have columns named `\0` `\v` etc.?

**Comment by lmeyerov** [comment]
I may be wrong, but I'd assume normalizing columns wreaks havoc; similar to wanting symbols in a compiler for consistency. 

The intuition is that users will have CSVs with the darndest things and we don't want to force them to spend an hour cleaning before they get started.

**Comment by briantrice** [comment]
Yeah, don't block them for sure. There's room for some kind of nicety, but I'm unsure what yet. Right now the expectation is that users have our JS editor with tab-completion, but that doesn't help if they designate names/formula through PyGraphistry.

**Comment by lmeyerov** [comment]
@thibaudh @briantrice can we close?

**Comment by lmeyerov** [comment]
@thibaudh Is the idea, for now, we push this to the data receiver for smarter error reporting?
