### ISSUE TITLE
Friendlier, action-oriented notifications for update availability

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#57]
Maybe we can provide a hint on how to update:

Today:
`A new version of PyGraphistry is available (installed=0.9.19 latest=0.9.22).`

Proposal:

"A new version of PyGraphistry is available (installed=0.9.19 latest=0.9.22). Try running `pip install "graphistry" --upgrade` or `pip install "graphistry[all]]" --upgrade`."

**Comment by thibaudh** [comment]
I thought about it decided against it. There are many ways to update a package (Anaconda, pip, virtual env, system/user) and we can’t guess the right one for the user.

**Comment by lmeyerov** [comment]
Makes sense. I had to run `pip2.7` for example :)
