### ISSUE TITLE
npm dataset handling slower and bigger filesize under api=2

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#58]
+ @thibaudh 

To reproduce: use `datasets/rawdata/all-npm-packages` notebook, and try api vs api=2

File size: 5mb vs 6mb

Time: maybe 10X difference? Seemed to be in python CPU processing.

**Comment by thibaudh** [comment]
I get 6mb for api=2 and 10mb for api=1. Are you that you uploaded the same data?

Api=1 fails during the upload (too much data for my home comcast), so I cannot comment on the time difference. That being said, Protobuf tries hard to encode strings well. Too hard, perhaps.

**Comment by thibaudh** [comment]
No news, and I suspect this is invalid. Closing
