### ISSUE TITLE
Question: what community detection coloring is being used

### ISSUE THREAD

**Issue by lukepereira** [graphistry/pygraphistry#582]
Hi there,

When plotting using `encode_point_color` on a non-existent categorical field, Graphistry assigns node colors that closely match communities that I would like to be using.

I have looked through the code but haven't been able to find which community detection algo (and params) is being used on this failure case. Note, they are not random, which is what happens when I don't call `encode_point_color`.

I have also checked the `g` object and don't see and info about the layout or colors.

Any help would be greatly appreciated.

Thanks

**Comment by lukepereira** [comment]
I was able to roughly reproduce these communities using Louvain with max 1 level

**Comment by lmeyerov** [comment]
Yes, exactly, we do a local vote to ensure speed by default

compute_cugraph(alg) can enrich quickly with alternative community labels
