### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'graphistry.models' on 0.35.0

### ISSUE THREAD

**Issue by theonmd** [graphistry/pygraphistry#616]
**Describe the bug**
A simple import seem to be failing on the latest 0.35.0 release. The issue does not appear when we downgrade to previous versions.

**To Reproduce**
Code, including data, than can be run without editing:

```python
import graphistry
```

**Expected behavior**
Successful import.

**Actual behavior**
Error message: `ModuleNotFoundError: No module named 'graphistry.models'`

Let me know if I'm doing something wrong, and thanks for the help!

**Comment by lmeyerov** [comment]
Thanks for the catch, we will work through!

**Comment by lmeyerov** [comment]
PR https://github.com/graphistry/pygraphistry/pull/617 fixes, and will publish once CI accepts

**Comment by theonmd** [comment]
Thanks for the quick resolution @lmeyerov!

**Comment by lmeyerov** [comment]
@theonmd 0.35.1 is up with the packaging fix, and merged to master as well
