### ISSUE TITLE
Cryptic error when the graph is empty (might be NetworkX specific)

### ISSUE THREAD

**Issue by thibaudh** [graphistry/pygraphistry#63]
From a user

```python
url= graphistry.bind(source="src", destination='dst',
node='nodeid').plot(digraph)
```

It gives me this error:
ValueError: Edge attribute "source" bound to "src" does not exist.

**Comment by briantrice** [comment]
Oh, that's an unfortunate failure mode.

**Comment by briantrice** [comment]
What kind of empty should be detected and dispatched on? Is it just no rows or something more fundamental?

**Comment by thibaudh** [comment]
The message above seems to indicate no edges.

Ideally, we should support no edges when a non-empty node table is given. That is basically a scatter plot.

**Comment by briantrice** [comment]
Thanks; just wondering whether there was something deeper and this was the first point in code to complain. I guess I can check zero nodes but zero edges needs to just accept the data as-is. [Best user feedback is show them the scatterplot so they understand it.]

**Comment by thibaudh** [comment]
As a note, I know ETL1 chokes on graphs with no edges. In this case, we did not get this far since this error comes from Pygraphistry.

**Comment by briantrice** [comment]
Thanks; I wasn't sure where an appropriate "raise" message would work.

**Comment by thibaudh** [comment]
Yes we have `util.error` which always throws an exception but also creates a red error box when running in Jupyter.
