### ISSUE TITLE
Biogrid demo is missing data

### ISSUE THREAD

**Issue by padentomasello** [graphistry/pygraphistry#64]
In the notebook BiogridDemo.ipynb, we attempt to load data with: 

```
rawdata = pandas.read_table('./data/BIOGRID-ALL-3.3.123.tab2.txt', na_values=['-'], engine='c')
```
but `BIOGRID-ALL-3.3.123.tab2.txt` does not exist in the directory folder. 

Thibaud, I'm happy to take, if you can let me know where the data is located.

**Comment by thibaudh** [comment]
Easy to fix. We don't need to commit the datafile since pandas can download CSVs over HTTP.

**Comment by thibaudh** [comment]
Btw, the notebook already has an explanation asking the user to download the data. The biogrid data is too large to be included in the repo: over 200 MB
