### ISSUE TITLE
Use Versioneer to manage version string

### ISSUE THREAD

**Issue by thibaudh** [graphistry/pygraphistry#66]
Following a discussion with @lsb, using Versioneer (https://github.com/warner/python-versioneer) to automatically pull version strings from git tags would 
 1. Simplify the release process
 2. Make it easier to automate release with Jenkins

**Comment by lmeyerov** [comment]
This looks quite nice. I'm wondering if there's a way we can use it for all the git-rooted modules, e.g., have it export a version.json? AFAICT, we'd have it in the main folder, but while it'd make a _version.py, we'd need to add an extra gen step.
