### ISSUE TITLE
setup.py should fail when the upload fails

### ISSUE THREAD

**Issue by lsb** [graphistry/pygraphistry#67]
Currently, we're seeing it return error code 0 when uploading a pre-existing package version.

**Comment by thibaudh** [comment]
I am seeing error code 1 locally. I don't think this is a setuptools issue.

**Comment by thibaudh** [comment]
It looks like this is an issue with Python 2.7.6. At least Python 2.7.10/3.4.X or later return the proper exit code.

Since we are the only ones publishing to PyPI, we can work around it. Marking as won't fix and closing.
