### ISSUE TITLE
Don't upload the same data twice, check if data has been uploaded before

### ISSUE THREAD

**Issue by thibaudh** [graphistry/pygraphistry#69]
Benefits:
- Faster plot() when tweaking encodings
- Notebooks are faster to rerun

**Comment by quinnhj** [comment]
Will this be tied into the REST data management API discussions? It sounded like we were heading towards treating datasets separately from workbooks/encodings, which looks in line with what you want to do here.

**Comment by thibaudh** [comment]
Yes and PyGraphistry can be taught to use the new REST endpoint eventually.

However, design discussions of the new REST API should not happen on this public repository.

**Comment by lmeyerov** [comment]
There are safety considerations around this optimization, wontfix for now.
