### ISSUE TITLE
Make an anaconda package

### ISSUE THREAD

**Issue by thibaudh** [graphistry/pygraphistry#7]

**Comment by lmeyerov** [comment]
Assigning thibaud. This is commercially relevant in that companies buy continuum.

**Comment by thibaudh** [comment]
Anaconda installs and is compatible with pip, so we are already installable by Anaconda users. Since our package does not have any native code, there is also no direct benefit to having an Anaconda package on top of our pip package, it would double the maintenance burden.

Closing until we have a good reason for maintaining an Anaconda package.
