### ISSUE TITLE
Can I run CUDA on my local machine with pygraphistry?

### ISSUE THREAD

**Issue by amirsani** [graphistry/pygraphistry#72]
I have a k40 active. I was curious if I can run pygraphistry on my local machine.

Thank you

**Comment by lmeyerov** [comment]
Hi @amirsani , this will use your local GPU (browser) for rendering, and calls out to the graphistry backend server for interactive analytics. We've been working with organizations for fully on-premise options, but that is currently only a commercial option. We may soon have an AWS option, feel free to contact about that!

**Comment by amirsani** [comment]
Great! Thank you. I have 2 k40c, so hopefully this will be sufficient for my initial work. AWS sounds like a great option for the next stage. 


Get Outlook for Android






On Fri, Sep 2, 2016 at 12:38 AM +0200, "lmeyerov" <notifications@github.com> wrote:












Hi @amirsani , this will use your local GPU (browser) for rendering, and calls out to the graphistry backend server for interactive analytics. We've been working with organizations for fully on-premise options, but that is currently only a commercial option. We may soon have an AWS option, feel free to contact about that!
