### ISSUE TITLE
API access key time for academic use !!

### ISSUE THREAD

**Issue by nasir44** [graphistry/pygraphistry#76]
Hello, 
I would like to ask for key access for using pygraphistry for academic use
  I would like to know how much time does it take to get the access key.
Is there some other way than email to request access key.
What kind of information is required for requesting access key

Thanks

**Comment by lmeyerov** [comment]
Hi @nasir44 we just saw the request here -- we primarily monitor the email address for API keys -- please contact info@graphistry.com and we'd be happy to set you up!

**Comment by prashantpawar** [comment]
Why do you guys do this? I don't understand. I 'signed up', but apparently it may take days for you to send me an API Key.

I am right now trying to find out a good library for my data visualization, but would I still be interested in using your library few days later when your key (may or may not) arrive? I dunno.

Why do you guys wanna deter usage by those who want to use their own local GPU? I don't want to use your exploration features.
