### ISSUE TITLE
[ValueError], about API key! !

### ISSUE THREAD

**Issue by RiptideBo** [graphistry/pygraphistry#84]
I run graphistry in python3.5, trying to use pandas.Dataframe data of edges-[’src‘,'dst','weight'] to plot my graph. 
But I encounted a ValueError as following:
------------------------------------------------------
File "E:\Python35\lib\site-packages\graphistry\pygraphistry.py", line 85, in authenticate
    util.error('API key not set explicitly in `register()` or available at ' + EnvVarNames['api_key'])
  File "E:\Python35\lib\site-packages\graphistry\util.py", line 83, in error
    raise ValueError(msg)
ValueError: API key not set explicitly in `register()` or available at GRAPHISTRY_API_KEY
------------------------------------------------------

code:
------------------------------------------------------
ploter = gr.bind(source='src', destination='dst')
ploter.plot(edgedata.ix[:,['src','dst']])
-------------------------------------------------------

How could I use it correctly? Or did I made any mistake? 

please help me!!!

**Comment by lmeyerov** [comment]
This sounds like you did not set your API key, "graphistry.register('mykeyhere')" -- ping us at pygraphistry@graphistry and we can get you setup!

**Comment by RiptideBo** [comment]
Thank you a lot. 
I am applying for it on email. 
Stephen Lee, 245885195@qq.com

**Comment by nihateee** [comment]
Hello,
I'd like to ask for API key for using pygraphistry my graduate project.
please help me !!

Thanks
