### ISSUE TITLE
Report server-side ETL errors to client 

### ISSUE THREAD

**Issue by thibaudh** [graphistry/pygraphistry#9]
Generally, add meaningful error messages when API is misused (missing edges, nodes, source, etc)

Also ask user to upgrade pygraphistry when API version has changed

**Comment by lmeyerov** [comment]
@thibaudh can we close / split the issue?

**Comment by thibaudh** [comment]
Still not resolved since it is a day of work. Will become more pressing as users get frustrated...

**Comment by lmeyerov** [comment]
This has been there for awhile now, closing.
