### ISSUE TITLE
Looking for a tool to render large graps, with filtering collapsible nodes and custom icons

### ISSUE THREAD

**Issue by 1001QAdotNET** [graphistry/pygraphistry#96]
Hi guys

I just came across your tool and I wanted to check with you before I start reading the docs if what I want is possible. Trying to save some time here as I am looking at more options at the same time (currently reading the docs for another candidate for this)

I have seen that D3.js can achieve the above but frankly speaking I am looking for a Python solution
I could probably export data to a format that D3.JS needs but I don't like this solution

Your libraries/module looks promising.
Can you please help me with a clarification?

**Comment by lmeyerov** [comment]
Graphistry supports all font-awesome icons, larger interactive visualization than any alternative we are aware, and filtering. Collapsing is not yet supported, though the direct connect tool has a notion of grouping.
